from pathlib import Path
import re,json
p=Path(r'C:\Users\KK\channel-audit-20261010\06_ANALYTICS\CHANNEL_FORENSIC_AUDIT')
f=p/'03_VIDEO_BY_VIDEO_AUDIT.md';s=f.read_text(encoding='utf-8-sig')
fix={'ALLEGATIONSlabel':'ALLEGATIONS label','Readabilityrisk':'Readability risk','ShowUNVERIFIED':'Show UNVERIFIED','UNKNOWNduration':'UNKNOWN duration','YouTubeCCstate':'YouTube CC state','alternativebrief':'alternative brief','authorizedproduction':'authorized production','continueddistribution':'continued distribution','contractreversal':'contract reversal','curveprocessing':'curve processing','designproperty':'design property','disputeddecision':'disputed decision','earlyretentionexport':'early retention export','exactretention':'exact retention','facelessformat':'faceless format','genericchannelbranding':'generic channel branding','givesDistroKid':'gives DistroKid','independentIPO':'independent IPO','measuredretentionUNKNOWN':'measured retention UNKNOWN','opposingposition':'opposing position','persistentCOMPLAINT':'persistent COMPLAINT','producedHarrison':'produced Harrison','saysNORULINGYET':'says NO RULING YET','stoparbitrations':'stop arbitrations','thatdeliveryfolder':'that delivery folder','underMORETHANABADUPLOAD':'under MORE THAN A BAD UPLOAD','viewsSuggested':'views Suggested','notgenericchannelbranding':'not generic channel branding','massre-render':'mass re-render','revoice orreupload':'revoice or reupload','nativeA/B':'native A/B','claimantsbecome':'claimants become','source-qualified':'source-qualified','actualframes':'actual frames','currentlive':'current live','paidvoice':'paid voice','newchannel':'new channel','isboring':'is boring','allfilms':'all films','fullwatch':'full watch','listen-through':'listen-through','Motionquality':'Motion quality','packagingpromise':'packaging promise','AA':'AA'}
for a,b in fix.items():s=s.replace(a,b)
# Separate prose number/word joins without touching paths, backtick fields or checksums.
ls=[]
for line in s.splitlines():
 if 'SHA' not in line and not any(t in line for t in ['C:/','512bb6','fb6e79','d643a4','03_VIDEOS','VIDEO_','video_']):
  line=re.sub(r'(?<=[A-Za-z])(?=\d)', ' ',line)
  line=re.sub(r'(?<=\d)(?=[A-Za-z])', ' ',line)
 ls.append(line)
f.write_text('\n'.join(ls)+'\n',encoding='utf8')
for fn in ['03_VIDEO_BY_VIDEO_AUDIT.md','06_PACKAGING_AND_RETENTION.md']:
 t=(p/fn).read_text(encoding='utf-8-sig');assert 'continuouscontinuous' not in t;assert '\ufffd' not in t;print(fn,len(t),'readable, no corrupted replacement sequences')
rows=json.loads((p/'video_shorts_probe.json').read_text())
notes={1:['Location before company; HOW IT STARTED needs context','INTERNAL MESSAGES needs context; source text tiny','CRITICISM TO SECURITY abstract without company','GPS ATTEMPT understandable object but defendant/context late','SEVEN GUILTY PLEAS promises outcome; opening says federal prosecutions','DPA IS NOT A CONVICTION requires legal familiarity','NOT A VERDICT correction needs prior claim','55.7M EXPLAINED offers financial stakes; settlement context follows','NO58.7M AWARD corrects a number unfamiliar viewer may not know','WHAT IT COST generic conclusion; legal-cost document tiny'],2:['Financial contrast clear; header absent at0s, present by3s','0s cashnumber;3s clauseheader and dense source','Dark0s;3s NOT A PENALTY needs previous misconception','Dark0s;3s NO FINAL NO YET depends on prior regulatory context','Dark0s;3s HOW THE DEAL ACTUALLY ENDED, company context in image small','Dark0s;3s3DAYS LATER1B; event preceding interval implicit','Dark0s;3s20B IS NOT1B clear number contrast but company small','Dark0s;3sFIGMA AFTER ADOBE recognizable companies, outcome vague'],3:['4562TRACKS clear number; claimant attribution not visible in firstframe','UPLOAD ONCE+distribution chain; ordinary viewer sees service function','THE STORY CHANGES generic; AI context in small source','1000/NEARLY2000 claims; next scene dark by3s','ISRC acronym before lay meaning; object reinforces recordings','THIS IS WHERE IT CHANGES needs prior context','DISTROKID:UMG IS WRONG identifies sides and denial','150000PERWORK strong stakes but conditional ceiling context required']}
a=['# Actual Shorts visual evidence','', 'All26local MP4s sampled at0s,3s,end-1.5s. No complete listening/watch-through. All1080x1920;all sampled story portions embed landscape16:9 picture in a narrow central band. This is a verified layout observation,not a causal swipe-rate finding. Hashes and dimensions in video_shorts_probe.json.','', '|Episode/Short|Runtime s|Observed opening issue/strength|Burned captions in samples|Ending sample|','|---|---:|---|---|---|']
c={1:0,2:0,3:0}
for r in rows:
 ep=r['episode'];i=c[ep];c[ep]+=1;a.append(f"|{ep:03d}/S{i+1:02d}|{r['duration']:.2f}|{notes[ep][i]}|{'Present,small within band' if ep==1 else 'Not observed'}|{'Full-screen documentary/subscribe CTA' if ep in [1,3] else 'Story graphic; no CTA at sampled instant'}|")
a += ['', 'Interpretation: alternate vertical layout and immediately meaningful frame should be tested on future contiguous extracts from the same long-form audio. Keep source/claim status. No existing upload or file was changed. Card presence does not prove related-video linkage or conversion. Optional YouTubeCC not established by rendered frames. Do not call absence at one ending sample absence everywhere.','', 'Contact sheets: video_shorts_001_contact.png,video_shorts_002_contact.png,video_shorts_003_contact.png. Individual frames: video_short_E_NN_C.png. Root report04contains live metrics and scheduling analysis.']
(p/'video_shorts_visual_notes.md').write_text('\n'.join(a)+'\n',encoding='utf8')
print('26-row visual evidence written')
